use std::fs;
use std::io::Write;
use std::path::PathBuf;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR not set");
    let etc_dir = PathBuf::from(&manifest_dir).join("etc");

    let cipher_file = etc_dir.join("cipher-mapping.txt");
    let sim_file = etc_dir.join("client-simulation.txt");

    println!("cargo:rerun-if-changed=build.rs");
    println!("cargo:rerun-if-changed={}", cipher_file.display());
    println!("cargo:rerun-if-changed={}", sim_file.display());

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    generate_ca_stores(&out_dir, &etc_dir).expect("Failed to generate CA stores");

    generate_client_profiles(&sim_file);

    let contents = fs::read_to_string(&cipher_file)
        .unwrap_or_else(|e| panic!("Failed to read {}: {}", cipher_file.display(), e));

    let dest_path = PathBuf::from(&out_dir).join("cipher_mapping_generated.rs");
    let mut out = fs::File::create(&dest_path)
        .unwrap_or_else(|e| panic!("Failed to create output file: {}", e));

    let mut entries: Vec<CipherEntry> = Vec::new();

    for (line_num, line) in contents.lines().enumerate() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        match parse_line(line) {
            Some(entry) => entries.push(entry),
            None => {
                eprintln!(
                    "build.rs: Warning: could not parse line {}: {:?}",
                    line_num + 1,
                    line
                );
            }
        }
    }

    writeln!(
        out,
        "// AUTO-GENERATED by build.rs from cipher-mapping.txt — DO NOT EDIT"
    )
    .unwrap();
    writeln!(out).unwrap();

    // --- CIPHER_MAP: new-style CipherInfo entries ---
    writeln!(out, "pub static CIPHER_MAP: &[CipherInfo] = &[").unwrap();
    for entry in &entries {
        writeln!(out, "    CipherInfo {{").unwrap();
        writeln!(out, "        hex_high: 0x{:02X},", entry.hex_high).unwrap();
        writeln!(out, "        hex_low: 0x{:02X},", entry.hex_low).unwrap();
        writeln!(out, "        openssl_name: {:?},", entry.openssl_name).unwrap();
        writeln!(out, "        iana_name: {:?},", entry.iana_name).unwrap();
        writeln!(out, "        protocol: {:?},", entry.protocol).unwrap();
        writeln!(out, "        key_exchange: {:?},", entry.key_exchange).unwrap();
        writeln!(out, "        auth: {:?},", entry.auth).unwrap();
        writeln!(out, "        encryption: {:?},", entry.encryption).unwrap();
        writeln!(out, "        key_bits: {},", entry.key_bits).unwrap();
        writeln!(out, "        mac: {:?},", entry.mac).unwrap();
        writeln!(out, "        is_export: {},", entry.is_export).unwrap();
        writeln!(out, "        pfs: {},", entry.pfs).unwrap();
        writeln!(out, "    }},").unwrap();
    }
    writeln!(out, "];").unwrap();
    writeln!(out).unwrap();

    // --- find_cipher using CIPHER_MAP ---
    writeln!(
        out,
        "pub fn find_cipher(hex_high: u8, hex_low: u8) -> Option<&'static CipherInfo> {{"
    )
    .unwrap();
    writeln!(
        out,
        "    CIPHER_MAP.iter().find(|c| c.hex_high == hex_high && c.hex_low == hex_low)"
    )
    .unwrap();
    writeln!(out, "}}").unwrap();
    writeln!(out).unwrap();

    // --- CIPHER_SUITES: legacy CipherSuite entries (backward compatibility) ---
    writeln!(out, "pub static CIPHER_SUITES: &[CipherSuite] = &[").unwrap();
    for entry in &entries {
        writeln!(out, "    CipherSuite {{").unwrap();
        writeln!(out, "        hex_high: 0x{:02X},", entry.hex_high).unwrap();
        writeln!(out, "        hex_low: 0x{:02X},", entry.hex_low).unwrap();
        writeln!(out, "        ossl_name: {:?},", entry.openssl_name).unwrap();
        writeln!(out, "        rfc_name: {:?},", entry.iana_name).unwrap();
        writeln!(out, "        tls_version: {:?},", entry.protocol).unwrap();
        writeln!(out, "        kx: {:?},", entry.key_exchange).unwrap();
        writeln!(out, "        auth: {:?},", entry.auth).unwrap();
        writeln!(out, "        enc: {:?},", entry.encryption).unwrap();
        writeln!(out, "        bits: {},", entry.key_bits).unwrap();
        writeln!(out, "        mac: {:?},", entry.mac).unwrap();
        writeln!(out, "    }},").unwrap();
    }
    writeln!(out, "];").unwrap();

    eprintln!(
        "build.rs: Generated {} cipher entries into {:?}",
        entries.len(),
        dest_path
    );
}

fn generate_ca_stores(
    out_dir: &str,
    etc_dir: &std::path::Path,
) -> Result<(), Box<dyn std::error::Error>> {
    let stores = [
        ("MOZILLA", "Mozilla.pem"),
        ("MICROSOFT", "Microsoft.pem"),
        ("APPLE", "Apple.pem"),
        ("JAVA", "Java.pem"),
        ("LINUX", "Linux.pem"),
    ];

    let out_file = format!("{}/ca_stores_generated.rs", out_dir);
    let mut output = String::from("// AUTO-GENERATED by build.rs — DO NOT EDIT\n\n");

    for (name, filename) in &stores {
        let pem_path = etc_dir.join(filename);
        println!("cargo:rerun-if-changed={}", pem_path.display());
        output.push_str(&format!(
            "pub static CA_{}: &[u8] = include_bytes!({:?});\n",
            name, pem_path
        ));
    }

    fs::write(out_file, output)?;
    Ok(())
}

struct CipherEntry {
    hex_high: u8,
    hex_low: u8,
    openssl_name: String,
    iana_name: String,
    protocol: String,
    key_exchange: String,
    auth: String,
    encryption: String,
    key_bits: u16,
    mac: String,
    is_export: bool,
    pfs: bool,
}

fn parse_hex_byte(s: &str) -> Option<u8> {
    let s = s.trim();
    let s = s
        .strip_prefix("0x")
        .or_else(|| s.strip_prefix("0X"))
        .unwrap_or(s);
    u8::from_str_radix(s, 16).ok()
}

fn parse_line(line: &str) -> Option<CipherEntry> {
    // Format variants:
    //   "     0xXX,0xYY - OSSL_NAME  IANA_NAME  PROTO  Kx=...  Au=...  Enc=...  Mac=...  [export]"
    //   " 0xXX,0xYY,0xZZ - OSSL_NAME  IANA_NAME  PROTO  Kx=...  Au=...  Enc=...  Mac=...  [export]"

    // Split at the first " - " separator
    let dash_pos = line.find(" - ")?;
    let hex_part = line[..dash_pos].trim();
    let rest = line[dash_pos + 3..].trim();

    // Parse hex bytes — can be 2 or 3 comma-separated hex values
    let hex_bytes: Vec<&str> = hex_part.split(',').collect();
    let (hex_high, hex_low) = match hex_bytes.len() {
        2 => {
            let high = parse_hex_byte(hex_bytes[0])?;
            let low = parse_hex_byte(hex_bytes[1])?;
            (high, low)
        }
        3 => {
            // 3-byte SSLv2 cipher codes: first byte is the "cipher kind", third byte is the value.
            // We store first byte as hex_high and third byte as hex_low.
            let high = parse_hex_byte(hex_bytes[0])?;
            let low = parse_hex_byte(hex_bytes[2])?;
            (high, low)
        }
        _ => return None,
    };

    // Tokenize the remainder: OSSL_NAME  IANA_NAME  PROTO  Kx=...  Au=...  Enc=...  Mac=...
    let tokens: Vec<&str> = rest.split_whitespace().collect();
    if tokens.len() < 6 {
        return None;
    }

    let openssl_name = tokens[0].to_string();
    let iana_name = tokens[1].to_string();
    let protocol = tokens[2].to_string();

    let mut key_exchange = String::new();
    let mut auth = String::new();
    let mut encryption = String::new();
    let mut key_bits: u16 = 0;
    let mut mac = String::new();
    let mut is_export = false;

    for token in &tokens[3..] {
        let token = token.trim();
        if token.eq_ignore_ascii_case("export") {
            is_export = true;
        } else if let Some(val) = token.strip_prefix("Kx=") {
            // Strip size hints like RSA(1024) -> RSA, DH(512) -> DH
            key_exchange = strip_size_hint(val).to_string();
        } else if let Some(val) = token.strip_prefix("Au=") {
            auth = val.to_string();
        } else if let Some(val) = token.strip_prefix("Enc=") {
            // Parse "AlgName(bits)" or just "AlgName"
            if let Some(paren_pos) = val.find('(') {
                let alg = &val[..paren_pos];
                let bits_str = val[paren_pos + 1..].trim_end_matches(')');
                encryption = alg.to_string();
                key_bits = bits_str.parse().unwrap_or(0);
            } else {
                encryption = val.to_string();
                key_bits = 0;
            }
        } else if let Some(val) = token.strip_prefix("Mac=") {
            mac = val.to_string();
        }
    }

    // Also check if EXPORT appears anywhere in the line
    if line.to_lowercase().contains("export") {
        is_export = true;
    }

    let pfs = is_pfs_kx(&key_exchange);

    Some(CipherEntry {
        hex_high,
        hex_low,
        openssl_name,
        iana_name,
        protocol,
        key_exchange,
        auth,
        encryption,
        key_bits,
        mac,
        is_export,
        pfs,
    })
}

/// Strip the size hint from key exchange values like "RSA(1024)" -> "RSA", "DH(512)" -> "DH"
fn strip_size_hint(s: &str) -> &str {
    if let Some(pos) = s.find('(') {
        &s[..pos]
    } else {
        s
    }
}

/// Returns true if the key exchange provides Perfect Forward Secrecy.
fn is_pfs_kx(kx: &str) -> bool {
    matches!(kx, "DH" | "ECDH" | "DHE" | "ECDHE" | "DHEPSK" | "ECDHEPSK")
}

// ─── Client Profiles Generation ───────────────────────────────────────────────

/// A parsed entry from client-simulation.txt
struct ClientProfileEntry {
    name: String,
    short: String,
    handshake_bytes: String,
    lowest_protocol: String,
    highest_protocol: String,
    requires_sha2: bool,
    current: bool,
    services: String,
}

/// Parse a quoted shell array element: `("some value")` → `some value`
fn extract_shell_string(s: &str) -> String {
    let s = s.trim();
    // Remove surrounding parens: ("...") or ("")
    let s = s.strip_prefix('(').unwrap_or(s);
    let s = s.strip_suffix(')').unwrap_or(s);
    // Remove surrounding quotes
    let s = s.trim_matches('"');
    s.to_string()
}

/// Parse hex protocol string like "0x0303" → 0x0303 as u16, returned as string "0x0303"
fn normalize_protocol(s: &str) -> String {
    let s = s.trim().trim_matches('"');
    s.to_string()
}

/// Parse requires_sha2 / current boolean: "(true)" or "(false)"
fn parse_bool_val(s: &str) -> bool {
    let inner = extract_shell_string(s);
    inner == "true"
}

fn generate_client_profiles(sim_file: &PathBuf) {
    let contents = match fs::read_to_string(sim_file) {
        Ok(c) => c,
        Err(e) => {
            eprintln!(
                "build.rs: Warning: could not read {}: {}",
                sim_file.display(),
                e
            );
            return;
        }
    };

    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR not set");
    let dest_path = PathBuf::from(&out_dir).join("client_profiles_generated.rs");
    let mut out = fs::File::create(&dest_path)
        .unwrap_or_else(|e| panic!("Failed to create client_profiles_generated.rs: {}", e));

    let profiles = parse_client_simulation(&contents);

    writeln!(
        out,
        "// AUTO-GENERATED by build.rs from client-simulation.txt — DO NOT EDIT"
    )
    .unwrap();
    writeln!(out).unwrap();
    writeln!(out, "pub static CLIENT_PROFILES: &[ClientProfile] = &[").unwrap();

    for p in &profiles {
        // Convert protocol strings like "0x0303" to Rust u16 literals
        let lowest = parse_protocol_hex(&p.lowest_protocol);
        let highest = parse_protocol_hex(&p.highest_protocol);

        writeln!(out, "    ClientProfile {{").unwrap();
        writeln!(out, "        name: {:?},", p.name).unwrap();
        writeln!(out, "        short: {:?},", p.short).unwrap();
        writeln!(out, "        handshake_bytes: {:?},", p.handshake_bytes).unwrap();
        writeln!(out, "        lowest_protocol: 0x{:04X},", lowest).unwrap();
        writeln!(out, "        highest_protocol: 0x{:04X},", highest).unwrap();
        writeln!(out, "        requires_sha2: {},", p.requires_sha2).unwrap();
        writeln!(out, "        current: {},", p.current).unwrap();
        writeln!(out, "        services: {:?},", p.services).unwrap();
        writeln!(out, "    }},").unwrap();
    }

    writeln!(out, "];").unwrap();

    eprintln!(
        "build.rs: Generated {} client profiles into {:?}",
        profiles.len(),
        dest_path
    );
}

fn parse_protocol_hex(s: &str) -> u16 {
    let s = s.trim();
    let s = s
        .strip_prefix("0x")
        .or_else(|| s.strip_prefix("0X"))
        .unwrap_or(s);
    u16::from_str_radix(s, 16).unwrap_or(0)
}

/// Parse all client profiles from the client-simulation.txt content.
/// The file uses a bash array syntax; we extract key=value-like assignments per profile block.
fn parse_client_simulation(content: &str) -> Vec<ClientProfileEntry> {
    let mut profiles: Vec<ClientProfileEntry> = Vec::new();

    let mut name = String::new();
    let mut short = String::new();
    let mut handshake_bytes = String::new();
    let mut lowest_protocol = String::from("0x0300");
    let mut highest_protocol = String::from("0x0303");
    let mut requires_sha2 = false;
    let mut current = false;
    let mut services = String::new();
    let mut in_profile = false;

    for line in content.lines() {
        let trimmed = line.trim();
        if trimmed.is_empty() || trimmed.starts_with('#') {
            continue;
        }

        if let Some(rest) = trimmed.strip_prefix("names+=(") {
            // Save previous profile if we have one
            if in_profile && !name.is_empty() && !handshake_bytes.is_empty() {
                profiles.push(ClientProfileEntry {
                    name: name.clone(),
                    short: short.clone(),
                    handshake_bytes: handshake_bytes.clone(),
                    lowest_protocol: lowest_protocol.clone(),
                    highest_protocol: highest_protocol.clone(),
                    requires_sha2,
                    current,
                    services: services.clone(),
                });
            }
            // Start new profile
            let val = format!("({}", rest);
            name = extract_shell_string(&val);
            short = String::new();
            handshake_bytes = String::new();
            lowest_protocol = String::from("0x0300");
            highest_protocol = String::from("0x0303");
            requires_sha2 = false;
            current = false;
            services = String::new();
            in_profile = true;
        } else if let Some(rest) = trimmed.strip_prefix("short+=(") {
            let val = format!("({}", rest);
            short = extract_shell_string(&val);
        } else if let Some(rest) = trimmed.strip_prefix("handshakebytes+=(") {
            let val = format!("({}", rest);
            handshake_bytes = extract_shell_string(&val);
        } else if let Some(rest) = trimmed.strip_prefix("lowest_protocol+=(") {
            let val = format!("({}", rest);
            lowest_protocol = normalize_protocol(&extract_shell_string(&val));
        } else if let Some(rest) = trimmed.strip_prefix("highest_protocol+=(") {
            let val = format!("({}", rest);
            highest_protocol = normalize_protocol(&extract_shell_string(&val));
        } else if let Some(rest) = trimmed.strip_prefix("requiresSha2+=(") {
            let val = format!("({}", rest);
            requires_sha2 = parse_bool_val(&val);
        } else if let Some(rest) = trimmed.strip_prefix("current+=(") {
            let val = format!("({}", rest);
            current = parse_bool_val(&val);
        } else if let Some(rest) = trimmed.strip_prefix("service+=(") {
            let val = format!("({}", rest);
            services = extract_shell_string(&val);
        }
    }

    // Save last profile
    if in_profile && !name.is_empty() && !handshake_bytes.is_empty() {
        profiles.push(ClientProfileEntry {
            name,
            short,
            handshake_bytes,
            lowest_protocol,
            highest_protocol,
            requires_sha2,
            current,
            services,
        });
    }

    profiles
}
