/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Scan options passed from JavaScript */
export interface JsScanOptions {
  checkProtocols?: boolean
  checkCiphers?: boolean
  checkVulnerabilities?: boolean
  checkCertificate?: boolean
  checkHttpHeaders?: boolean
  checkForwardSecrecy?: boolean
  checkServerDefaults?: boolean
  checkServerPreference?: boolean
  checkClientSimulation?: boolean
  checkGrease?: boolean
  checkRating?: boolean
  /** Timeout in seconds */
  timeout?: number
  /** Connection timeout in seconds */
  connectTimeout?: number
  sni?: string
  /** "smtp"|"imap"|"pop3"|"ftp"|"ldap"|"xmpp"|"postgres"|"mysql" */
  starttls?: string
  ipv6?: boolean
  parallel?: number
}
export interface JsProtocolResults {
  ssl2?: boolean
  ssl3?: boolean
  tls10?: boolean
  tls11?: boolean
  tls12?: boolean
  tls13?: boolean
}
export interface JsVulnResult {
  /** "VULNERABLE" | "not_vulnerable" | "unknown" | "N/A" */
  status: string
  /** The CVE identifiers, may be empty */
  cve: Array<string>
  details: string
}
export interface JsVulnerabilityReport {
  heartbleed?: JsVulnResult
  ccsInjection?: JsVulnResult
  robot?: JsVulnResult
  poodle?: JsVulnResult
  tlsFallback?: JsVulnResult
  sweet32?: JsVulnResult
  freak?: JsVulnResult
  drown?: JsVulnResult
  logjam?: JsVulnResult
  beast?: JsVulnResult
  lucky13?: JsVulnResult
  crime?: JsVulnResult
  breach?: JsVulnResult
  rc4?: JsVulnResult
  ticketbleed?: JsVulnResult
  secureRenegotiation?: JsVulnResult
  winshock?: JsVulnResult
}
export interface JsCipherResult {
  /** e.g. "0xC0,0x2C" */
  hexCode: string
  opensslName: string
  ianaName: string
  protocol: string
  keyExchange: string
  bits: number
  pfs: boolean
  isExport: boolean
}
export interface JsCertificateReport {
  subject: string
  issuer: string
  san: Array<string>
  notBefore: string
  notAfter: string
  daysLeft: number
  expired: boolean
  selfSigned: boolean
  fingerprintSha256: string
  keyType: string
  keyBits: number
  signatureAlgorithm: string
  mustStaple: boolean
}
export interface JsHttpHeaderReport {
  hsts?: string
  hstsMaxAge?: number
  hpkp?: string
  xFrameOptions?: string
  xContentTypeOptions?: string
  csp?: string
  server?: string
  cookieFlags: Array<string>
}
export interface JsRatingDetails {
  numericScore: number
  baseGrade: string
  protocolScore: number
  keyExchangeScore: number
  cipherStrengthScore: number
  warnings: Array<string>
  appliedRules: Array<string>
}
export interface JsScanResult {
  target: string
  ip: string
  rdns?: string
  protocols?: JsProtocolResults
  vulnerabilities?: JsVulnerabilityReport
  certificate?: JsCertificateReport
  ciphers?: Array<JsCipherResult>
  httpHeaders?: JsHttpHeaderReport
  /** "A+", "A", "A-", "B", "C", "D", "E", "F", "T", "M", "?" */
  rating?: string
  /** Structured rating details (SSL Labs-compatible scoring). */
  ratingDetails?: JsRatingDetails
  scanDurationMs: number
  errors: Array<string>
}
/** Parse a scan target URI into [host, port] components. */
export declare function parseTarget(uri: string): Array<string>
/** Get the library version. */
export declare function version(): string
export declare class TlsScanner {
  /** Create a new TlsScanner instance. */
  constructor()
  /**
   * Scan a target host with the given options.
   *
   * `target` may be "host", "host:port", or "https://host:port/"
   */
  scan(target: string, options?: JsScanOptions | undefined | null): Promise<JsScanResult>
  /** Quick scan: only protocols + certificate. */
  quickScan(target: string): Promise<JsScanResult>
  /** Scan multiple targets sequentially. */
  scanBatch(targets: Array<string>, options?: JsScanOptions | undefined | null): Promise<Array<JsScanResult>>
  /** Run only vulnerability checks on a target. */
  checkVulnerabilities(target: string): Promise<JsVulnerabilityReport>
  /** Run only certificate check on a target. */
  checkCertificate(target: string): Promise<JsCertificateReport>
  /** Enumerate cipher suites supported by a target. */
  enumerateCiphers(target: string): Promise<Array<JsCipherResult>>
  /** Return the library version string. */
  static version(): string
}
